### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by peepsnet** [michelem09/wassup#5]
PHP Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; UADetector has a deprecated constructor in /wp-content/plugins/wassup/lib/uadetector.class.php on line 45
Dec 06, 16:16:42
PHP Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WassupItems has a deprecated constructor in /wp-content/plugins/wassup/lib/main.php on line 1482
Dec 06, 16:16:42
PHP Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; wDetector has a deprecated constructor in /wp-content/plugins/wassup/lib/main.php on line 179
Ignore
Dec 06, 16:16:42
PHP Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; wassup_pagination has a deprecated constructor in /wp-content/plugins/wassup/lib/main.php on line 29

wordpress 4.9.1, 
wassup Version 1.9.4.2

**Comment by michelem09** [comment]
Please Wassup and PHP version.

**Comment by peepsnet** [comment]
Sorry...
updated OP

**Comment by hdunk** [comment]
fixed in v1.9.4.3
